# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

resources:
  repositories:
  - repository: tox
    type: github
    endpoint: theochem
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
      py37:
        image: [linux, windows, macOs]
      py36:
        image: [linux, windows, macOs]
      build:
        py: '3.6'
      flake8:
        py: '3.6'
      black:
        py: '3.6'
