package:
  version: "{{ PROJECT_VERSION }}"
  name: 'grid'

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python ={{ MYCONDAPY }}
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
    - matplotlib
  run:
    - python
    - scipy
test:
  requires:
    - nose
  commands:
    - conda inspect linkages grid
    - nosetests -v --detailed-errors grid

about:
  description: Legacy grid module from HORTON 2
  home: https://github.com/theochem/grid
  license: GPLv3

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
